apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dnsrecords.easyaas.dev
spec:
  scope: Namespaced
  group: easyaas.dev
  names:
    kind: DnsRecord
    singular: dnsrecord
    plural: dnsrecords
    shortNames:
      - dns
    categories:
      - easyaas

  versions:
    - name: v1
      served: true
      storage: true

      additionalPrinterColumns:
        - name: Dns Name
          type: string
          description: The number of pods launched by the MyApp
          jsonPath: .spec.dnsName
        - name: Ready
          type: string
          description: Whether the record is fully registered
          jsonPath: .status.conditions[?(@.type == 'Ready')].status
        - name: Reason
          type: string
          description: Reason why the record is not ready
          jsonPath: .status.conditions[?(@.type == 'Ready')].reason
        - name: Age
          type: string
          description: Age
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dnsName:
                  type: string
                type:
                  type: string
                  enum:
                    - A
                    - AAAA
                    - CNAME
                    - TXT
                records:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                  x-kubernetes-preserve-unknown-fields: true
                ready:
                  type: boolean
                kopf:
                  type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
