version: "3.8"
services:
  git-repo:
    build:
      context: ..
      dockerfile: reposerver/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server_blocks:/opt/bitnami/openresty/nginx/conf/server_blocks:ro
      - /var/log/easyaas:/easyaas/logs
      - ../terraform:/easyaas/terraform
