apiVersion: batch/v1
kind: Job
metadata:
  name: terraform
spec:
  template:
    spec:
      containers:
        - name: tf
          image: easyaas-registry.web:12345/terragrunt-runner
          imagePullPolicy: Always
          env:
            - name: TERRAGRUNT_CONFIG
              value: /app/terragrunt-config/terragrunt.hcl
          volumeMounts:
            - name: terragrunt-config
              mountPath: /app/terragrunt-config
      restartPolicy: Never
      volumes:
        - name: terragrunt-config # This will be updated with the unique configmap info generated for the job
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
