apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: terraformresources.core.easyaas.dev
spec:
  scope: Namespaced
  group: core.easyaas.dev
  names:
    categories:
      - easyaas
    kind: TerraformResource
    plural: terraformresources
    singular: terraformresource
    shortNames:
      - tfr
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                terraform:
                  type: object
                  properties:
                    source:
                      type: string
                crd:
                  type: string
                extraEnvVariables:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
              required:
                - crd
                        
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                  x-kubernetes-preserve-unknown-fields: true
                ready:
                  type: boolean
                kopf:
                  type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
