version: '3.1'

services: 
  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3,route53
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  git-repo:
    build:
      context: ..
      dockerfile: local-testing/repository.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server_blocks:/opt/bitnami/openresty/nginx/conf/server_blocks:ro
      - /var/log/easyaas:/easyaas/logs
      - ../terraform:/easyaas/terraform
