{{ range $role := .Values.easyaasResourceParams.roles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Release.Name}}-{{ $role.name}}
  namespace: {{ $role.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $role.name }}
subjects:
  - kind: ServiceAccount
    name: {{ template "serviceAccount.name" $ }}
    namespace: {{ $.Release.Namespace }}
{{ end }}
