# Permission specific for the job
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-job-terraform-backend
  namespace: {{ .Release.Namespace }}
rules:
  # Allow create and watch k8s secrets for the terraform backend
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
    resourceNames:
    #   # Note: This must match the value defined for the backend in terragrunt.hcl
      - tfstate-default-easyaas-{{ .Release.Name }}

  # Permissions not scoped to a specific secret
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list

  # Lease for terraform lock
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - create
      - delete
      - watch
      - patch
      - update

    resourceNames:
      - lock-tfstate-default-easyaas-{{ .Release.Name }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name}}-jobs-terraform-backend
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name}}-job-terraform-backend
subjects:
  - kind: ServiceAccount
    name: {{ template "serviceAccount.name" . }}
    namespace: {{ .Release.Namespace }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "serviceAccount.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{ .Values.serviceAccount.annotations | toYaml | indent 4 }}
  labels:
{{ .Values.serviceAccount.labels | toYaml | indent 4 }}
